name:                notes
version:             0.1.0.0
github:              "thulsadum/notes"
license:             BSD3
author:              "Sebastian Claus"
maintainer:          "sbstncls@gmail.com"
copyright:           "Apache 2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thulsadum/notes#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- time
- directory
- strict

library:
  source-dirs: src

executables:
  notes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notes

tests:
  notes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notes
    - hspec
